config/routes.rb
Rails.application.routes.draw do
  resources :topics, only: [:index, :show]

  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  get 'about', to: 'pages#about'
  get 'gallery', to: 'pages#gallery'

  resources :blogs do
      member do 
        get  :toggle_status
      end
  end
  
  mount ActionCable.server => '/cable'

  root to: 'pages#home'
end

app/views/shared/_application_footer.html.erb
<div class="mastfoot">
  <div class="inner">
    <p class="app-footer"><%= copyright_generator %></p>
  </div>
</div>

app/views/shared/_application_nav.html.erb
<div class="masthead clearfix">
  <div class="inner nav-style">
    <nav class="nav nav-masthead">
      <%= link_to "Home", root_path, class: 'nav-link' %>
      <%= link_to "About", about_path, class: 'nav-link' %>
      <%= link_to "Gallery", gallery_path, class: 'nav-link' %>
      <%= link_to "Blog", blogs_path, class: 'nav-link' %>
      <%= login_helper('nav-link') unless current_page? root_path%>
    </nav>
  </div>
</div>

app/views/shared/_blog_nav.html.erb
   <nav class="navbar navbar-toggleable-md navbar-inverse fixed-top bg-inverse">
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>


      <a class="navbar-brand" href="<%= root_path %>">The Adams Adventures</a>


      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
             <%= link_to "About", about_path, class: 'nav-link' %>
             <%= link_to "Gallery", gallery_path, class: 'nav-link' %>
             <%= login_helper('nav-link') %>
        </ul>
      </div>
    </nav>

app/views/shared/_blog_sidebar.html.erb
<div class="col-md-3 offset-md-1 blog-sidebar">
  <div class="sidebar-module sidebar-module-inset image-set">
    <%= image_tag "elise.jpg", height: "160", width: "150", alt: "Picture of Elise Adams", class: "thumb-image" %>
    <p class="sidebar-para">Hi, my name is Elise. I love blogging and sharing my thoughts, exeriences, and adventures. I am a software developer who is passionate about changing lives. I am obsessed with Harry Potter and the magical world. I look forward to Taco Tuesdays. I have the worlds greated husband and the best support system.</p>
  </div>

<!--   <div class="sidebar-module topic-side-bar">
    <h4 class="head-topic">Topics</h4>
    <% @set_sidebar_topics.each do |topic| %>
      <p class="auth-links btn btn-outline-info hovering-effect topic-side"><%= link_to topic.title, topic_path(topic) %></p>
   <% end %>
  </div> -->

    <%= source_helper("alert alert-info blog-sidebar-source") %>

  <div class="sidebar-module">
    <h4 class="centering">Follow Me</h4>
    <ol class="list-unstyled social-links">
    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-4 social-icon">
            <li><a href="https://github.com/liseyadams" target="_blank"><%= fa_icon "github" %></a></li>
            <li><a href="https://twitter.com/LiseyAdams" target="_blank"><%= fa_icon "twitter-square" %></a></li>
            <li><a href="https://www.facebook.com/elise.neuman.5" target="_blank"><%= fa_icon "facebook-square" %></a></li>
        </div>
        <div class="col-md-4 social-icon">
            <li><a href="https://www.pinterest.com/lovelylisey28/" target="_blank"><%= fa_icon "pinterest" %></a></li>
            <li><a href="https://www.linkedin.com/in/elise-adams-8265ba13a/" target="_blank"><%= fa_icon "linkedin-square" %></a></li>
            <li><a href="https://www.instagram.com/liseyadams/" target="_blank"><%= fa_icon "instagram", class: "instagram-icon" %></a></li>
        </div>
      <div class="col-sm-2"></div>
      </div>
    </ol>
  </div>
</div>

app/views/shared/_carousel.html.erb
  <div id="myCarousel" class="carousel slide" data-ride="carousel">
<!--       <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
      </ol> -->
    <div class="carousel-div">
      <div class="card carousel-inner" role="listbox">
        <div class="card carousel-item active">
        <%= image_tag "shoes.JPG", alt: "kaden and elise's shoes" %>
        </div>
        <div class="card carousel-item">
          <%= image_tag "married.jpg", alt: "couple wedding pictures" %>
        </div>
        <div class="card carousel-item">
          <%= image_tag "dancing.JPG", alt: "Couple dancing" %>
        </div>
    </div>
  </div>

app/views/shared/_nav.html.erb
<div class ="<%= location %>">
  <div><%= link_to "Home", root_path %></div>
  <div><%= link_to "About", about_path %></div>
  <div><%= link_to "Gallery", gallery_path %></div>
  <div><%= link_to "Blog", blogs_path %></div>
</div>