config/routes.rb
Rails.application.routes.draw do
  resources :topics, only: [:index, :show]

  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  get 'about', to: 'pages#about'
  get 'gallery', to: 'pages#gallery'

  resources :blogs do
      member do 
        get  :toggle_status
      end
  end
  
  mount ActionCable.server => '/cable'

  root to: 'pages#home'
end

app/views/pages/about.html.erb
<div class="app-card-container">
  <div class="card">
      <div class="row">
        <div class="col-md-3">
          <div class="image-adjust">
              <%= image_tag "couple.jpg", height: "500", width: "390", alt: "Couple standing on dixie rock", class: 'profile-img' %>
            </div>
          </div>

 
            <div class="col-md-9 text-adjust">
              <p>My name is Elise Adams. I am a full time software developer who loves blogging on the side. This is my lovely husband Kaden. Together we make the Adams family (*cue the music). We love taking adventures together and hope to show you some along the way. We are both entrepreneurs. I just formed a business with BigMouthFrogDev. This blog is actually built by yours truly.
              </p>

               <p>Take a gander into our blog. We hope to give you insight on starting a business, technology, diy's, and pretty much anything that comes to our minds. Mostly we want to share this for our friends and family so they may keep in touch as everyone's lives tend to take different paths.
               </p>

               <p>
               A little about us:
               </p>

               <p>Elise is obsessed with all things Harry Potter and the magical world. She loves everything about fall. Her biggest passion in life is software development and to help others achieve their dreams.
               </p>

               <p>Kaden loves persuing his dreams and making them a reality. He love everything about cars and can name off pretty much anything you can think of that has to do with them. He loves drawing out houseplans and wants to build our dream home.
               </p>

              <hr>

              <p>
              xoxo,
              </p>

              <p>
              The Adams Family 
              </p>
            </div>
          </div>
     </div>
  </div>

app/views/pages/gallery.html.erb
<div class="row card-sizing">
  <% @photos.each do |photo| %>
    <div class="col-md-4 card-sizing">
      <div class="card " data-id="<%= photo.id %>">
        <%= link_to (image_tag photo.main_image, width: '100%' , height: '100%'), blog_path(photo), class: "gallary-card" %>
      </div>
    </div>
  <% end %>
</div>

<!-- <div>
  <a class="auth-links btn btn-outline-info hovering-effect" href="/gallery">Back to top</a>
</div> -->

app/views/pages/home.html.erb
<!-- <div class="inner cover"> -->
<!--     <div class="row home-row"> -->
      <div class="home-card card">
       <link href="https://fonts.googleapis.com/css?family=Vibur" rel="stylesheet">
          <h2 class="btn btn-lg btn-block button-style btn-responsive"><a class= "blog-link" href="<%= blogs_path %>"> The Adams Family Blog</a></h2>
        <div class="row nav-rowing">
            <div class="links-home"><%= link_to "About", about_path %></div>
            <div class="links-home"><%= link_to "Gallery", gallery_path %></div>
            <div class="links-home"><%= link_to "Blog", blogs_path %></div>
          </div>
        </div>
<!--   </div> -->
<!-- </div> -->