config/routes.rb
Rails.application.routes.draw do
  resources :topics, only: [:index, :show]

  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  get 'about', to: 'pages#about'
  get 'gallery', to: 'pages#gallery'

  resources :blogs do
      member do 
        get  :toggle_status
      end
  end
  
  mount ActionCable.server => '/cable'

  root to: 'pages#home'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title><%= @page_title %></title>
    <%= csrf_meta_tags %>

    <meta name="keywords" content="<%= @seo_keywords %>" />

    <link href="https://fonts.googleapis.com/css?family=Abel" rel="stylesheet">


    <%= favicon_link_tag 'favicons/flowers.png' %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'relxoad' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
     <div class="site-wrapper">

      <div class="site-wrapper-inner">

        <div class="cover-container">

        <div id="background"></div>

          <%= render "shared/application_nav" unless current_page? root_path %>

          <%= yield %>

          <%= render "shared/application_footer" unless current_page? root_path %>

          <%= alerts %>

          <%= source_helper("application") %>
        </div>
      </div>
  </div>

  </body>
</html>

app/views/layouts/blog.html.erb
<!DOCTYPE html>
<html>
  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title><%= @page_title %></title>
    <%= csrf_meta_tags %>

    <link href="https://fonts.googleapis.com/css?family=Abel|Shadows+Into+Light" rel="stylesheet">

    <meta name="keywords" content="<%= @seo_keywords %>" />

    <%= favicon_link_tag 'favicons/flowers.png' %>

    <%= stylesheet_link_tag    'blogs', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
      
      <%= render 'shared/blog_nav' %>
  <div>
      <%= render 'shared/carousel' %>
  </div>

    <div class="card blog-header">
      <div class="heading">
          <h1 class="blog-title">Kaden + Elise</h1>
          <p class="lead blog-description">Soul-Mates, Adventures, &amp; Memories</p>
      </div>
        <div class="offset-3 write-new">
         <span>
          <%= link_to 'Write A New Blog Post', new_blog_path, class: "auth-links btn btn-outline-info hovering-effect"  if logged_in?(:site_admin) %>
         </span>
        </div>
         <div class="topic-label">
         <span>
           <%= link_to "Topics", topics_path, class: "auth-links btn btn-outline-info hovering-effect" %>
         </span>
       </div>
    </div>
    
    <div class="container">
      <div class="row">
          <%= yield %>
          <%= render 'shared/blog_sidebar' %>
      </div>
    </div>
   

    <footer class="blog-footer">
      <p><%= render "shared/application_footer" %></p>
      <p>
        <a class="auth-links btn btn-outline-info hovering-effect" href="<%= blogs_path %>">Back to top</a>
      </p>
    </footer>
  </body>
</html>